default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: db/development
  host: localhost
  username: Mahou
  password:

# test:
#   <<: *default
#   database: db/test
#   host: localhost
#   username: Mahou
#   password:
